version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: chat_app
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        extra_hosts:
            - "host.docker.internal:host-gateway"

    db:
        image: mysql:8.0
        container_name: chat_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
